pub enum Opcode {
    Return = 0,
    Constant,
    Negate,
    Add,
    Subtract,
    Multiply,
    Divide,
    Nil,
    True,
    False,
    Not,
    Equal,
    Greater,
    Less,
    LogicalAnd,
    LogicalOr,
    BitwiseAnd,
    BitwiseOr,
    Print,
    Pop,
    DefineGlobal,
    GetGlobal,

    Unknown,
}

pub fn from_u8(x: u8) -> Opcode {
    match x {
        0 => Opcode::Return,
        1 => Opcode::Constant,
        2 => Opcode::Negate,
        3 => Opcode::Add,
        4 => Opcode::Subtract,
        5 => Opcode::Multiply,
        6 => Opcode::Divide,
        7 => Opcode::Nil,
        8 => Opcode::True,
        9 => Opcode::False,
        10 => Opcode::Not,
        11 => Opcode::Equal,
        12 => Opcode::Greater,
        13 => Opcode::Less,
        14 => Opcode::LogicalAnd,
        15 => Opcode::LogicalOr,
        16 => Opcode::BitwiseAnd,
        17 => Opcode::BitwiseOr,
        18 => Opcode::Print,
        19 => Opcode::Pop,
        20 => Opcode::DefineGlobal,
        21 => Opcode::GetGlobal,
        _ => Opcode::Unknown,
    }
}
